# Generated by Django 5.0.6 on 2024-07-10 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='created',
            field=models.DateTimeField(auto_created=datetime.datetime(2024, 7, 10, 11, 51, 35, 607949, tzinfo=datetime.timezone.utc)),
        ),
    ]
