# Generated by Django 5.0.6 on 2024-07-11 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogauthor_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='created',
            field=models.DateTimeField(auto_created=datetime.datetime(2024, 7, 11, 11, 52, 36, 871719, tzinfo=datetime.timezone.utc)),
        ),
    ]
