# Generated by Django 5.0.6 on 2024-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogauthor_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
