# Generated by Django 5.0.6 on 2024-07-06 22:09

import book.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to=book.helpers.SaveMedia.save_book_image_path),
        ),
    ]
